dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:2.7.18')
    implementation project(':holiday-core-java')
    implementation project(':holiday-spring-starter')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

// Override for Java 8 target
tasks.withType(JavaCompile).configureEach {
    options.release = 8
}
